server:
  port:8106
spring:
  application:
    name: inube-registry-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframwork.security: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
